version: '3'

services:
  jenkins:
    image: bluestorm1288/jenkins-ansible
    container_name: jenkins
    build:
      context: jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  remote_host:
    image: remote_host
    container_name: remote_host
    build:
      context: remote_host
    volumes:
      - "$PWD/remote_host/backup-db-script.sh:/tmp/backup-db-script.sh"
    networks:
      - net
  db_host:
    image: mysql:5.7
    container_name: db
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
    ports:
      - "3306:3306"  
  ansible_web:
    image: ansible_web
    container_name: ansible_web
    build:
      context: ansible_web
    ports:
      - "8088:80"  
    networks:
      - net

networks:
  net:
    name: net