version: '3'

services:
  jenkins:
    image: bluestorm1288/jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    image: remote_host
    container_name: remote_host
    build:
      context: centos7
    networks:
      - net

networks:
  net: