version: '3'

services:
  jenkins:
    image: bluestorm1288/jenkins-ansible
    container_name: jenkins
    build:
      context: jenkins-ansible
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    image: remote_host
    container_name: remote_host
    build:
      context: remote_host
    # To keep the oracle-linux container running  
    command: tail -f /dev/null  
    volumes:
      - "$PWD/remote_host/backup-db-script.sh:/tmp/backup-db-script.sh"
    networks:
      - net
  db_host:
    image: mysql:5.7
    container_name: db
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net  
networks:
  net: