#!/bin/sh

# Start the Python script in the background
python3 /data/gitea/home/webhook_handler.py > /data/gitea/home/webhook_handler.log 2>&1 &

# The exec command below is not strictly necessary, but it's often used to ensure proper logging and process handling.
exec s6-svscan /etc/s6