version: '3'
services:
  alpine-git-ssh:
    image: bluestorm1288/git-server
    container_name: git-server
    ports:
      - "2222:22"
    command: "/usr/sbin/sshd -D"
    networks:
      - jenkins-data_net
networks:
  jenkins-data_net:
    external: true   
